### ISSUE TITLE
Walls near bottom look a bit ugly

### ISSUE THREAD

**Issue by Talon1024** [Calinou/godot-reflection#9]
The walls near the bottom of the map look ugly. The bottom half of the wall is lit up brightly, and the upper half is almost black. For me, this is a bit off-putting and ugly.

**Comment by Calinou** [comment]
Can you take some screenshots?

~~This can likely be resolved by increasing floor roughness (and decreasing metallic), which will make reflections less noticeable.~~

**Comment by Talon1024** [comment]
![editor_screenshot_2022-12-26T134253](https://user-images.githubusercontent.com/6550500/209576156-4595c42b-0c19-4265-9dcd-6593659eec83.png)
![editor_screenshot_2022-12-26T134325](https://user-images.githubusercontent.com/6550500/209576180-56ffe788-e90e-4340-b4ed-aea44aff7d33.png)

Notice the light gradients at the bottom of the walls? Unless there are lights on the floor lighting up that particular part of the wall, it looks ugly and nonsensical.

I was able to work around the issue by adding a very large upward-facing plane below all the level geometry.

**Comment by Calinou** [comment]
That's SDFGI light leaking, which can indeed be fixed by ensuring the level geometry is manifold (two-sided). This also occurs with VoxelGI.

> I was able to work around the issue by adding a very large upward-facing plane below all the level geometry.

Can you open a pull request with these changes? Thanks in advance :slightly_smiling_face:
